ALTER TABLE `address_private` ADD `jobtitle` VARCHAR(255) NOT NULL ,
ADD `locationcode` VARCHAR(255) NOT NULL ,
ADD `businessunit` VARCHAR(255) NOT NULL ,
ADD `department` VARCHAR(255) NOT NULL ,
ADD `business_address` VARCHAR(255) NOT NULL ,
ADD `business_phone_nr` VARCHAR(255) NOT NULL ,
ADD `business_city` VARCHAR(255) NOT NULL ,
ADD `business_phone_nr_2` VARCHAR(255) NOT NULL ,
ADD `business_state` VARCHAR(255) NOT NULL ,
ADD `business_fax_nr` VARCHAR(255) NOT NULL ,
ADD `business_zipcode` VARCHAR(255) NOT NULL ,
ADD `business_mobile_nr` VARCHAR(255) NOT NULL ,
ADD `business_country` VARCHAR(255) NOT NULL ,
ADD `business_car_phone` VARCHAR(255) NOT NULL ,
ADD `business_email` VARCHAR(255) NOT NULL ,
ADD `phone_nr_2` VARCHAR(255) NOT NULL ,
ADD `other_address` VARCHAR(255) NOT NULL ,
ADD `other_phone_nr` VARCHAR(255) NOT NULL ,
ADD `other_city` VARCHAR(255) NOT NULL ,
ADD `other_phone_nr_2` VARCHAR(255) NOT NULL ,
ADD `other_state` VARCHAR(255) NOT NULL ,
ADD `other_fax_nr` VARCHAR(255) NOT NULL ,
ADD `other_zipcode` VARCHAR(255) NOT NULL ,
ADD `other_mobile_nr` VARCHAR(255) NOT NULL ,
ADD `other_country` VARCHAR(255) NOT NULL ,
ADD `alternative_name`  VARCHAR(255) NOT NULL ,
ADD `timestamp_birthday` VARCHAR(255) NOT NULL ,
ADD `suffix` VARCHAR(255) NOT NULL ,
ADD `pobox_state` VARCHAR(255) NOT NULL ,
ADD `pobox_country` VARCHAR(255) NOT NULL ,
ADD `other_email` VARCHAR(255) NOT NULL,
ADD `opt_assistant_name` VARCHAR(255) NOT NULL,
ADD `opt_assistant_phone_nr` VARCHAR(255) NOT NULL;

ALTER TABLE `address_businesscards` ADD `suffix` INT( 11 ) NOT NULL ,
ADD `jobtitle` VARCHAR( 255 ) NOT NULL ,
ADD `website` VARCHAR( 255 ) NOT NULL ,
ADD `business_phone_nr_2` VARCHAR( 255 ) NOT NULL ,
ADD `business_country` VARCHAR( 255 ) NOT NULL ,
ADD `business_car_phone` VARCHAR( 255 ) NOT NULL ,
ADD `personal_phone_nr_2` VARCHAR( 255 ) NOT NULL ,
ADD `personal_country` VARCHAR( 255 ) NOT NULL ,
ADD `other_address` VARCHAR( 255 ) NOT NULL ,
ADD `other_zipcode` VARCHAR( 255 ) NOT NULL ,
ADD `other_city` VARCHAR( 255 ) NOT NULL ,
ADD `other_state` VARCHAR( 255 ) NOT NULL ,
ADD `other_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `other_phone_nr_2` VARCHAR( 255 ) NOT NULL ,
ADD `other_fax_nr` VARCHAR( 255 ) NOT NULL ,
ADD `other_mobile_nr` VARCHAR( 255 ) NOT NULL ,
ADD `other_email` VARCHAR( 255 ) NOT NULL ,
ADD `pobox` VARCHAR(255) NOT NULL ,
ADD `pobox_country` VARCHAR(255) NOT NULL ,
ADD `pobox_state` VARCHAR(255) NOT NULL ,
ADD `pobox_zipcode` VARCHAR(255) NOT NULL ,
ADD `pobox_city` VARCHAR(255) NOT NULL ,
ADD `other_country` VARCHAR( 255 ) NOT NULL,
ADD `opt_assistant_name` VARCHAR(255) NOT NULL,
ADD `opt_assistant_phone_nr` VARCHAR(255) NOT NULL;

ALTER TABLE `address_private` ADD `opt_callback_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_company_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_company_name` VARCHAR( 255 ) NOT NULL ,
ADD `opt_manager_name` VARCHAR( 255 ) NOT NULL ,
ADD `opt_pager_number` VARCHAR( 255 ) NOT NULL ,
ADD `opt_profession` VARCHAR( 255 ) NOT NULL ,
ADD `opt_radio_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_telex_number` VARCHAR( 255 ) NOT NULL ;

ALTER TABLE `address_businesscards` ADD `opt_callback_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_company_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_company_name` VARCHAR( 255 ) NOT NULL ,
ADD `opt_manager_name` VARCHAR( 255 ) NOT NULL ,
ADD `opt_pager_number` VARCHAR( 255 ) NOT NULL ,
ADD `opt_profession` VARCHAR( 255 ) NOT NULL ,
ADD `opt_radio_phone_nr` VARCHAR( 255 ) NOT NULL ,
ADD `opt_telex_number` VARCHAR( 255 ) NOT NULL ;

ALTER TABLE `address` ADD `suffix` INT( 11 ) NOT NULL ,
ADD `pobox_state` VARCHAR( 255 ) NOT NULL ,
ADD `pobox_country` VARCHAR( 255 ) NOT NULL ;
