CREATE TABLE IF NOT EXISTS `cms_data_revisions` (
  `id` int(11) NOT NULL auto_increment,
  `parentPage` int(11) NOT NULL default '0',
  `pageTitle` varchar(255) default NULL,
  `pageLabel` varchar(255) default NULL,
  `datePublication` int(11) default '0',
  `pageData` mediumtext,
  `pageRedirect` varchar(255) default NULL,
  `isPublic` tinyint(3) default '1',
  `isActive` tinyint(3) default '1',
  `isMenuItem` tinyint(3) default '1',
  `keywords` varchar(255) default NULL,
  `apEnabled` int(11) default '0',
  `isTemplate` tinyint(3) default '0',
  `isList` tinyint(3) default '0',
  `useMetaData` tinyint(3) default '0',
  `isSticky` tinyint(3) default '0',
  `search_fields` varchar(255) default NULL,
  `search_descr` varchar(255) default NULL,
  `isForm` tinyint(3) default '0',
  `date_start` int(11) default '0',
  `date_end` int(11) default '0',
  `date_changed` int(11) default '0',
  `notifyManager` varchar(50) default '0',
  `isGallery` tinyint(3) default '0',
  `pageRedirectPopup` tinyint(3) default NULL,
  `popup_data` varchar(255) default NULL,
  `new_code` mediumtext,
  `new_state` char(2) default NULL,
  `search_title` varchar(255) default NULL,
  `search_language` varchar(255) default NULL,
  `search_override` tinyint(3) default NULL,
  `pageAlias` varchar(255) default NULL,
  `isSpecial` varchar(1) default NULL,
  `date_last_action` int(11) default NULL,
  `google_changefreq` varchar(255) default 'monthly',
  `google_priority` varchar(255) default '0.5',
  `autosave_info` varchar(255) NOT NULL,
  `autosave_data` mediumtext NOT NULL,
  `address_ids` varchar(255) default NULL,
  `address_level` tinyint(3) default NULL,
  `isProtected` int(11) NOT NULL,
  `useSSL` tinyint(3) NOT NULL,
  `useInternal` tinyint(3) NOT NULL,
  `isFeedback` tinyint(3) default NULL,
  `pageHeader` text NOT NULL,
  `autosave_header` text NOT NULL,
  `isShop` tinyint(3) NOT NULL,
  `shopPrice` float(16,2) NOT NULL,
  `isSource` tinyint(3) default NULL,
  `page_id` int(11) NOT NULL,
  `versiondate` int(11) unsigned NOT NULL,
  `editor` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
);
